### ISSUE TITLE
new: Pagination

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#62] opened 2018-06-15 12:21 UTC
## Problem Statement

As a customer i would like an easy way to see what page i am on, how many pages there are and and then navigate between them so i can find the things i want easily rather than infinite scroll

## Recommendation

![image](https://user-images.githubusercontent.com/9420407/41467550-3b6599d2-70a7-11e8-9690-2e707ba82ecf.png)
![image](https://user-images.githubusercontent.com/9420407/41467555-407a6312-70a7-11e8-8acb-69fb8e8d4d99.png)

## Designs

none - infinite scroll in most places

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url)
 
* Which teams/applications do you think would use this improvement?
MOB MYACCOUNT
* High impact: No

**Comment by invalidred** [comment] 2018-10-31 17:48
Do we have a design reference for pagination? Is there a team that currently uses pagination?

**Comment by DJDA** [comment] 2018-10-31 19:54
I think login and registration (Strikeforce) mentioned during a My TELUS showcase a while back that role management required pagination and was in the roadmap ?  Maybe @ivaylogabrovsky could comment?

**Comment by varunj90** [comment] 2018-11-12 16:31
from DPA Dev leads meeting:

Apurv from myTelus was working on the design and only his team has the need for it, all other squads need it, but low priority. 

Other squads may have a need for this later.

**Comment by invalidred** [comment] 2018-11-29 14:07
## Phase 1:

Pagination should be a responsive stateless component. It will receive the following props (let's chat about alternative prop/approaches if needed)

1. current - current page number
2. pageSize - number of data items per page
3. total - total number of data items
4. onChange - callbackFunc(nextPage)

## Expected Behaviour

### Initial Render
The parent component will provide pageSize, total and current page properties. Based on these values we will compute the number of page blocks to render based on the width of the container the pagination component will be in (*TODO*: confirm with designer about width size). So if each page block is 20px (for example) and `<Prev` and `Next>` take 25px and the parent width is 200px then we can render up-to (200px - 50px (prev/next))/20px = 7 page-blocks. Also if the total number of pages is greater than max renderable page-blocks (which is 7 in our example), then we will need to render 6 page blocks and an ellipses block. For example if total pages = 8 and max renderable page blocks is 7 then we will render `<Prev``1``2``3``4``5``...``8``Next>`. 

### On Page Block Click
When a page block is clicked we'll fire the `onChange` event callback function and pass the next page to load. So if the user is currently on page 2 and clicks on `Next>` we should call `onChange` function and pass the value 3. However if the user is on page 2 and click on page 5 and we should call `onChange` function with value 5. However if the user is on page 5 and clicks on page 5 again, then we should NOT trigger onChange event handler.

### Responsiveness
This component needs to be aware of view-port using `<Responsive/>` tds component or something similar and compute page blocks to render for mobile, tablet and desktop views. In mobile view for example, we may want bigger button (*TODO*: confirm with designer) also we may render fewer page blocks.


## Phase 2:

More Features
- Making it stateful
- Current number of items on page: so for example if there are 100 items in total and we show 10 items page page, click on page 2 should show words `11 - 20 items` next to pagination component. This will give the user an idea of how many items there are and which one they are looking at.

**Comment by Berjesty** [comment] 2018-12-05 17:22
**Context:**

- We’ve discovered a limitation in our design systems which causes a customer pain-point during long the  period where there are more content than what they are viewing on the page. 

**Goal:**
- Design and build a process to separate the content into discrete pages so that its is digestible, easy to understand for customers.

**AC:** 
- When I enter a page that has been divided into 10 pages, 
I will see "1" "2" "3" "4" "..." "16" "Next >". 

- When I enter a page that has been divided into 10 pages and click on "2" 
I will see "< Prev" "1" "2" "3" "4" "..." "10" "Next >". 

- When I enter a page that has been divided into 10 pages and click on "3" 
I will see "< Prev" "1" "2" "3" "4" "5" "..." "10" "Next >". 

- When I enter a page that has been divided into 10 pages and click on "4" 
I will see "< Prev" "1" "..." "4" "5" "6" "7" "..." "10". 

- When I enter a page that has been divided into 10 pages and click on "5" 
I will see "< Prev" "1" "..." "5" "6" "7" "8" "..." "10" "Next >". 

- When I enter a page that has been divided into 10 pages and click on "6" 
I will see "< Prev" "1" "..." "6" "7" "8" "9" "10" "Next >".

**Comment by sketchidea** [comment] 2019-02-01 19:50
@Berjesty could you give me access to inspect mode on the Invision project for this component? Thanks!

**Comment by Berjesty** [comment] 2019-02-04 16:55
@sketchidea for sure, sent you an Invision invite and added you the project.

**Comment by varunj90** [comment] 2019-03-12 13:52
hi @Berjesty since this ticket is in development (both design & dev), and @sketchidea is developing it, can you add the final design to DSM. 

@sketchidea hope you're working off Berjesty's design file

**Comment by Christina-Lo** [comment] 2019-04-05 17:16
@sketchidea here's an invision link (inspect mode) for reference on the changes Jordan has provided https://telus.invisionapp.com/d/main#/console/13362811/356557071/inspect

**Comment by varunj90** [comment] 2019-04-22 18:25
Pagination component is now available!
Release notes https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-pagination%401.0.0
sketch: Design System Manager: tds_community v1.0.17

**Closed** 2019-04-22 18:25 UTC
Labels: priority: low, status: completed :boom:, type: new component :gift:

**Comment by ah-arch** [comment] 2019-05-03 19:58
Just some feedback:
- When there is only 1 panel, it crashes with the error `TypeError: t.props.children.map is not a function`.
- [WCAG 2.1 guidelines](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html) for target sizes are 44px by 44px, but the buttons are set to 32px by 32px for mobile.
