### ISSUE TITLE
Toggle (Mobile View)

### ISSUE THREAD

**Issue by DanGenuardi** [telus/tds-community#112] opened 2018-09-19 20:12 UTC
## Problem statement

Enhance ToggleSwitch with upgraded functionality and design to make it more usable while accommodating business needs

## Recommendation

Enhance existing ToggleSwitch component with more features like: loading state, adding optional tooltip, moving label to the left

## Design intent

Toggle switches are digital on/off switches. They prompt users to choose between two mutually exclusive options and always have a default value. Toggles should provide immediate results. They are best used for changing the state of system functionalities and preferences.

## Designs

![toggle-switch-design](https://user-images.githubusercontent.com/26413531/60363074-89ff1400-99b0-11e9-9f29-2e63aaea9738.png)

Design reference: https://telus.invisionapp.com/share/T5SFO08PCWF#/screens
Source working file: https://invis.io/a/ZC5LFDEMB9Q6

## Acceptance criteria

Given I am displaying the ToggleSwitch Component

      When browser renders ToggleSwitch
      Then it should present label on the left side from toggle switch
      And toggle switch is displayed at the far right of the container with a left margin of 16px
      And toggle switch white circle button must have a shadow (`0px 0px 2px 0 #000`) around it according to new design

      When I supply optional tooltip
      Then the tooltip should render to the right of the label with left margin of 8px

      When I supply `isLoading` prop to ToggleSwitch component
      Then the small green spinner should be displayed on top of the toggle switch only

Given a user is interacting with the ToggleSwitch

      When a user clicks the toggle
      Then toggle animates (but stays grey)
      And spinner appears
      And async action completes
      And spinner disappears
      And toggle turns green

### Accessibility

      When browser renders ToggleSwitch
      Then semantically it should be presented as a `<button role="switch" aria-checked="false" aria-labelledby="xxx">`
      And the styles for `on` and `off` states should be dictated by `aria-checked` state

Example for styling:

```
[role="switch"][aria-checked="true"] {
  ...styles for "on" state...
}
[role="switch"][aria-checked="false"] {
  ...styles for "off" state...
}
```

More details about this accessibility decision can be found through this article: [Building Inclusive Toggle Buttons](https://www.smashingmagazine.com/2017/09/building-inclusive-toggle-buttons/)

## Meta

- Include component name and version: vX.Y.Z
- Willing to design solution: Yes/No
- Willing to develop solution: Yes/No
- Has workaround: Yes/No
- Do any similar components already exist in TDS (core or community): Yes/No (link)
- Which teams/applications do you think would use this improvement?
- High impact: Yes/No

**Comment by varunj90** [comment] 2018-09-24 20:03
@Berjesty to chat with @DanGenuardi regarding the design and bring back to dpa!

**Comment by Berjesty** [comment] 2018-09-26 17:42
@DanGenuardi Moving the toggle to the right side for ease of usability perspective is great however to promote clarity of the status of the toggle, it should be in close proximity. My suggestion is to move the status closer to the toggle to prevent confusion.

**Comment by owestinTelus** [comment] 2018-09-28 13:07
The proposed solution does not have any negative accessibility concerns. 

* moving the trigger to the near right on a mobile screen (as opposed to below) is still reasonably discoverable
* the toggle design is consistent with what we use elsewhere on the site and the visible state is understandable

The text state of the toggle may be more clear if it was closer to the toggle itself but I don't think that's required. The terms 'disabled' vs 'on' can be misleading if they are associated with an on/off toggle

If the text label is specific to the 'Data Access' and 'Overage protection' then it could be immediately to the right of the text or below it.

**Comment by theetrain** [comment] 2018-09-28 17:28
This is related to #29 and #113 

Once we have an approved design, we can enhance the yet-released community-toggle component.

**Comment by DanGenuardi** [comment] 2018-10-02 14:45
We are already using toggles within the desktop and tablet layouts. We are not planning on switching to checkboxes for when a customer views this portion of the site on a mobile device. Is there a way we can set up a meeting to discuss this?

**Comment by DanGenuardi** [comment] 2018-10-03 15:43
![screen shot 2018-10-03 at 11 41 45 am](https://user-images.githubusercontent.com/39997967/46422060-82505e80-c701-11e8-8d85-48ddb91297d0.png)
 Does this explain it differently on how it's supposed to work?

**Comment by DanGenuardi** [comment] 2018-10-03 15:53
![screen shot 2018-10-03 at 11 50 55 am](https://user-images.githubusercontent.com/39997967/46422712-ed4e6500-c702-11e8-9646-68c10a4afb98.png)

or does this fix the problem?

**Comment by jesdavpet** [comment] 2018-10-03 16:54
Hey @DanGenuardi I think it may be more clear to continue this conversation in person, and just follow up with the consensus here on GitHub afterwards. I'll reach out to schedule some time with you, and @Berjesty as well.

**Comment by DanGenuardi** [comment] 2018-10-04 19:02
![screen shot 2018-10-04 at 3 00 27 pm](https://user-images.githubusercontent.com/39997967/46496556-5bb82380-c7e6-11e8-9e05-2fcccf6f2460.png)

I had the discussion with @jesdavpet about a possible fix for this mobile toggle experience we came to the conclusion that this approach would work best.

**Comment by jesdavpet** [comment] 2018-10-05 14:15
Thanks for following up @DanGenuardi !

This design iteration resolves the technical considerations I had raised above. Simplifying the scope in this way makes it a minor layout variant of the existing `@tds/community-toggle-switch` component, which has already been created.

@lucylist @Berjesty @DougTelus I think it's down to the design review process on this one now.

**Comment by DougTelus** [comment] 2018-10-05 14:33
I like this iteration. It gives an extra bit of visual clarity.

**Comment by Berjesty** [comment] 2018-10-05 15:00
Thanks Dan! I'm all good with this version as well all. @lucylist thoughts?

**Comment by DJDA** [comment] 2018-10-19 21:50
Hi all,

Some thoughts for all on this - I implemented elements of this design on the new RA Usage page for Family Manager aka "Data Manager 2".

In the reference mentioned above (https://www.nngroup.com/articles/toggle-switch-guidelines/), what has been termed "value" by @lucylist is here defined as "state descriptor".  I've ben describing it as "toggle context", or perhaps more formally, it can be thought of having the role of ["aria-describedby"](https://developers.google.com/web/fundamentals/accessibility/semantics-aria/aria-labels-and-relationships#aria-describedby)(in fact, that's how it's implemented for accessibility in RA Usage).

In essence, "describedby" text provides additional context to what "ON" and "OFF" mean for the toggle.  It’s only required when on/off are not unambiguous based on the constant label text alone. 

Take Nutella's usage project an example - ON always has "describedby" of “ON”, but OFF can represent multiple block states (billcycle blocked, data manager blocked, WCC blocked, …).  We need this additional "describedby" text to give context to what "OFF" means in this situation for the customer.

In my view, an ideal design does not require "describedby" text - ideally the label and the on/off should give enough context.  Furthermore, for accessibility and clarity, I would argue that the toggle label should be mandatory and not change when the toggle is flipped.  This is supported by the [Apple human interface design guidelines for Switches](https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/), which specify that for toggles, "Switches are either on or off. Providing labels that describe these states is redundant and clutters the interface".  I'd advocate for this advice above being included in our design guidelines: consistency between mobile web and native helps reduce friction for our customers.


### In summary:
I support the idea that we should have:
- ideal design are toggles that are in a pure two column table layout in mobile, with text to the left and the switch to the right, and nothing more
- the left text be defined the "label", for consistency with HTML5 and accessibility, and also that it be constant (i.e. it not change when the toggle is flipped).
- in the less desirable case that we need to provide additional context to "ON" and "OFF", we could have secondary "described-by" text that changes when the toggle is flipped to provide additional context
- Regardless of the optional inclusion of "describedby" text, the toggle is always in line with the label text.  See image below (and apologies in advance for it's rudimentary look and feel - I can only get so far with "Preview" on Mac 😬 )

![image](https://user-images.githubusercontent.com/2502296/47245262-91ecca00-d3c6-11e8-8077-3e5c1fb68a2e.png)

**Comment by lucylist** [comment] 2018-10-22 19:56
The Digital Platform Ambassadors met today and have discussed the toggle switch enhancements. Rather than have this issue focus on the naming etc. the main focus of this ticket is to make sure that left/right label/context is available for the swtich. we need to build this enhancement into the community component.

the design leads have agreed that the switch needs to align with context/value text

**Comment by Berjesty** [comment] 2018-11-19 20:19
This component is added to DSM library with definition, usage criteria and style examples. 
![toggle](https://user-images.githubusercontent.com/25160096/48732753-74519100-ec0e-11e8-933c-310ba170a9d5.png)

**Comment by varunj90** [comment] 2018-11-26 21:32
Toggle Mobile View design with David, Abdul and Berjesty w.r.t accessibility
- Align on standards - what is static, whats dynamic
- The usage of the toggle
- Accessibility concerns for devs in scenario 1 and 2
- Requirements need to be addressed and design can be updated

Next steps
- David and Berjesty to work together and list down the requirements
- Involve boskar

**Comment by Berjesty** [comment] 2019-01-17 21:12
Updated designs and context (usage criteria) in TDS Community Library based on the feedback and discussion around accessibility concerns. This issue has been addressed from design perspective.

**Comment by invalidred** [comment] 2019-03-11 19:45
So had a discussion with @Apurv Ray and here is a summary

![Toggle - new](https://user-images.githubusercontent.com/5270458/54152867-9f0d6280-4414-11e9-9805-4acfcdfd156e.png)


1. We will have a `label` on left side of the _ToggleSwitch_ that will never change that talks about what the _ToggleSwitch_ represents example: (Do you want paper bill ?)
2. We will show a `value/description` string that will be right below the `label` that talks about current status of the operation (Paper bill enabled, paper bill disabled)
3. The _ToggleSwitch_ will be inline with `value/description` string. @Apurv Ray suggested that it should _NOT_ be inline with `label` as this will allow for longer labels without colliding into the _ToggleSwitch_
4. We will address accessibility using `<A11yContent />` component like so
```
<ToggleSwitch 
  id="42" 
  name="paperBill" 
  value="paperBill"
  checked={true}
  label="wifi setting" 
  currentState={<Text>enabled<AllyContent>wifi settings: wifi is enabled</AllyContent></Text>}
/>
```

**Comment by donnavitan** [comment] 2019-03-22 16:52
As per our touch base with @owestinTelus @invalidred, we need to realign on the problem we're trying to solve. I'm just capturing some notes for reference:
* The original ask had 2 items for discussion: moving the toggle to the right, and adding a status below the label.
* Further discussion grew around the addition or inclusion of value/description and the a11y considerations surrounding it's use. As per Oskar's feedback, a toggle that properly uses a checkbox will natively address any a11y issues.
* Design discussion also included that adding the value/description provided visual clarity. However, it may also add to visual noise.

Furthering reading references, a couple mentioned previously in threads:
https://www.nngroup.com/articles/toggle-switch-guidelines/
https://scottaohara.github.io/aria-switch-button/
https://www.smashingmagazine.com/2017/09/building-inclusive-toggle-buttons/
https://www.sarasoueidan.com/blog/toggle-switch-design/
 
Related toggle issues/discussions:
https://github.com/telus/tds-community/issues/182
https://github.com/telus/tds-community/issues/153
https://github.com/telus/tds-community/issues/112
https://github.com/telus/tds-community/issues/29
https://github.com/telus/tds-community/pull/113

**Comment by jesdavpet** [comment] 2019-03-22 19:11
**Question:** if the toggle UI component is *so difficult* for customers to decipher visually, that we need to resort to text hints to describe it as "on" / "off" ... isn't the UX of a toggle already pretty clearly broken?

What value *does* a toggle provide that a checkbox *does not*?

**Comment by donnavitan** [comment] 2019-03-27 17:23
As per my discussions with Apurv and @invalidred, we've agreed to the following:
* Design review if label can be regular (I will take this away and provide examples for review at the next DPA). May be similar to a singular checkbox (i.e. I consent). May lose same level hierarchy with like form fields. 
* Agree to not include value description (native behaviour for checkbox will suffice). Examples have been provided that used the value description but these are considered not necessary.
* Agree to move toggle to the right (mobile/desktop)
* Agree to move switch to the right (on, green), switch to the left (off, grey)
* Will need to provide usage criteria (use for binary yes/no questions, do not use for a choice of different items). The label/question should be worded in such a way that the answer must be a yes or no. Otherwise, use something else.

Next steps:
* Get design approval first
* Will connect with @invalidred to make the updates

**Comment by donnavitan** [comment] 2019-03-27 17:57
Hello @jesdavpet, we do find value in having a toggle as it provides a better UX experience. The biggest UX value is having an instantaneous response to user action. Visually, the toggle is "switched on" and the expectation is that user action has been applied.

Addressing prior comments, we've agreed to take up some of the suggestions. As for the other comments, we'll provide better documentation and usage criteria as to how/when to use a toggle which we hope will mitigate any further confusion.

Further reading:
* https://www.nngroup.com/articles/toggle-switch-guidelines/
* https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8
* https://uxmovement.com/buttons/when-to-use-a-switch-or-checkbox/

As always, design is ever changing and while we try to build our components as robust/reusable as possible, they're open to improvement.

**Comment by donnavitan** [comment] 2019-04-16 17:47
As per discussions and a11y considerations, we've agreed to the following:

Toggle switches are digital on/off switches. They prompt users to choose between two mutually exclusive options and always have a default value. Toggles should provide immediate results. They are best used for changing the state of system functionalities and preferences.

Usage criteria
- Must provide concise, non-neutral label
- Use positive, active wording for the label; make clear what will happen by turning it on
- May group similar toggles; grouped toggles do not affect each other as each toggle provides on/off states for a specific option
- Inline tooltip is not mandatory to toggle label

Implementation 
- Programmatically use the checkbox element
- Group toggles using fieldset, and legend to provide a group heading
- Toggle will expand 100% width of its parent container
- Align toggle label to the left
- Align toggle glyph to the right
- Vertically align the toggle label and glyph to the top
- Inline tooltip will follow existing usage criteria

![TDS-Community-112_Toggle_20190416](https://user-images.githubusercontent.com/21316148/56232135-0fc82000-604e-11e9-8d5b-876e3d62f6ca.png)

**Comment by jesdavpet** [comment] 2019-04-17 23:17
Thanks for the follow up @donnavitan.

BTW, I really like the consideration that's been put into the component-level design you posted! 
🔥🔥🔥

Regarding this requirement ...
> Implementation:
> - Programmatically use the checkbox element

@invalidred Do you think from a code perspective it would make more sense to consider this component as a button element, rather than a form input element?

In retrospect, I feel like a lot of the confusion around the first iteration of this component has stemmed from it being considered a form input, which carries certain semantics and constraints that are _at odds_ with the stated design intent.

If the component is a button (in code, but styled to _look like_ a toggle), and it completes an action as soon as it is pressed (and not waiting until a form is submitted) then that makes total sense semantically. But, if the component is a checkbox, then it's state should not be processed until the whole form is submitted.

By requiring this to be implemented as a checkbox, wouldn't we essentially be creating a form without a submit button? This seems at odds with best practices for semantic markup, and kind of an `"HTML 101"` level misunderstanding to me.
_See:_ https://www.w3.org/TR/WCAG-TECHS/H32

**Comment by invalidred** [comment] 2019-04-18 12:54
@jesdavpet i think you are correct, a button makes perfect sense since one of the design intents is:

> Toggles should provide immediate results. 

So an `<input type="checkbox"/>` does not innately provide immediate result, it needs to be wrapped in a form with a `<button type="submit" />` to make the change happen; as you've correct identified.

BTW I did some research and found:

1. [Inclusive Design Component](https://inclusive-components.design/toggle-button/) _ToggleButton_ uses a button to represent a `<ToggleSwitch />` like component.
2. [Ant Design](https://ant.design/components/switch/) switches use `<buttons />` as can been seen in the screen shot below

![Screen Shot 2019-04-18 at 8 48 04 AM](https://user-images.githubusercontent.com/5270458/56362064-f1c9ff00-61b6-11e9-8426-646331317a02.png)

Now the issue we will face (if we choose to use a `<button />` as our source of `<ToggleSwitch/>`) is grouping `<ToggleSwitches/>`. Previously we were thinking of grouping `<ToggleSwitch/>` in a fieldset, I am unclear if we can use that.  I believe I will need to talk with @donnavitan & @apurvray about this, and probably setup a meeting with you in it, if you are up for it @jesdavpet ?

**Comment by invalidred** [comment] 2019-04-24 13:07
Implementation details revisited:

1. Use `<button />` with _role="switch"_,  _aria-checked="true|false"_ and _aria-labelledby="element"_ attributes instead of `<input />` 
`<button role="switch" aria-checked="true" aria-labelledby="notify-email">`
2. Use a `<span>` instead of a `<label>` to label the `<ToggleSwitch/>` as labels are used for [_input_](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) elements only
3. Group `<ToggleSwitch/>` in plain old `<ul>/<li>` instead of a `<fieldset />` elements as screen readers already know how to group items when they are in a list. Also _[fieldset](https://www.w3schools.com/tags/tag_fieldset.asp)_ only group form elements.
4. We can use a `<heading/>` above a grouped `<ToggleSwitches/>` to name the group.

**Comment by donnavitan** [comment] 2019-04-24 16:42
Thank @invalidred and @jesdavpet for thorough addressing of concerns! As per our discussion and as noted, we'll have to take the following back to design review. Expanding the two designs concerns further:
* Loading state for toggle: Use existing designs if possible. May use existing spinner component (apply on toggle only). Else, more options needed.
* Should "label" be clickable. Preferably, we want a solution that doesn't rely on workarounds. But if we want to maintain expected behaviour similar to checkbox/radio, then we need to make the toggle label clickable. Otherwise, we need to explore increasing the size of the toggle to be a bigger hit area.

We'll look into it!

**Comment by donnavitan** [comment] 2019-05-02 15:45
As per discussion with @apurvray and Ani, we're working on enhancing TDS core spinner component to allow use on smaller interactive elements beyond the button element. It can be used for toggle to indicate loading state.

**Comment by varunj90** [comment] 2019-05-27 20:30
@invalidred hey abdul what is the latest on this?

**Comment by donnavitan** [comment] 2019-05-27 20:37
As per discussion with @apurvray and @Christina-Lo, I'll be updating this with designs.

**Comment by donnavitan** [comment] 2019-06-10 19:09
Updated the designs to include the loading states which will use the spinner component.

Toggle switches are digital on/off switches. They prompt users to choose between two mutually exclusive options and always have a default value. Toggles should provide immediate results. They are best used for changing the state of system functionalities and preferences.

### Usage criteria
- Must provide concise, non-neutral label
- Use positive, active wording for the label; make clear what will happen by turning it on
- May group similar toggles; grouped toggles do not affect each other as each toggle provides on/off states for a specific option
- Inline tooltip is not mandatory to toggle label
- Inline tooltip will follow existing usage criteria

### Implementation
- Please refer to @invalidred for coding
- Toggle will expand 100% width of its parent container
- Align toggle label to the left
- Align toggle glyph to the right
- Vertically align the toggle label and glyph to the top
- Inline tooltip will follow existing usage criteria
- The toggle switch knob should animate from one side to the other when changing states
- The toggle switch background colour should fade into the other when changing states
- Spinner will only cover the toggle glyph
- Use [InputFeedback](https://tds.telus.com/components/index.html#inputfeedback) to provide further feedback management

![image](https://user-images.githubusercontent.com/21316148/59219782-4bd0ba80-8b91-11e9-87ce-427d5e65fcd1.png)

Design reference: https://telus.invisionapp.com/share/T5SFO08PCWF#/screens
Source working file: https://invis.io/a/ZC5LFDEMB9Q6

**Comment by agorovyi** [comment] 2019-06-28 18:16
@sketchidea and I updated the story and it needs to be reviewed by a designer and moved to Dev queue if approved.

cc: @donnavitan @apurvray @varunj90

**Comment by donnavitan** [comment] 2019-06-28 19:41
@sketchidea @agorovyi @apurvray @varu @Christina-Lo 

Made the following change:
* From "When I supply `isLoading` prop to ToggleSwitch component
  Then the toggle switch should be blurred and the spinner should be displayed on top of it"
* To "When I supply `isLoading` prop to ToggleSwitch component
  Then the small green spinner should be displayed on top of the toggle switch only"

No blurring please. Thanks!

**Comment by agorovyi** [comment] 2019-09-05 15:30
@nicmak I've added an **Accessibility** section to the **Acceptance Criteria** that will require some refactoring. Moved this back to dev.

**Comment by donnavitan** [comment] 2019-09-06 18:37
- Updated description to include content for documentation to add/update in the TDS Community code component section.
- Also added the implementation content for reference

**Comment by varunj90** [comment] 2019-09-30 19:17
This has been released in code and DSM.
Release notes: https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-toggle-switch%402.0.0

**Closed by varunj90** 2019-09-30 19:17 UTC
Labels: priority: medium, status: DPA design approved, type: new component :gift:

**Comment by donnavitan** [comment] 2019-09-30 19:19
v1.0.5 TDS Community DSM is released: [https://telus.invisionapp.com/dsm/telus/tds-community/releases](https://telus.invisionapp.com/dsm/telus/tds-community/releases)

**ToggleSwitch is now officially available in design and code**
Toggle switches are digital on/off switches. They prompt users to choose between two mutually exclusive options and always have adefault value. Toggles should provide immediate results. They are best used for changing the state of system functionalities and preferences.

- Updated design name in alignment with code
- Available as a single ToggleSwitch or a group ToggleSwitches
- Also available with inline Tooltip (must manually align)
- Thank you Apurv for providing designs
- [https://tds.telus.com/community/index.html#toggleswitch](https://tds.telus.com/community/index.html#toggleswitch)
