### ISSUE TITLE
new: quote/testimonial card

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#47] opened 2018-06-14 13:14 UTC
## Problem Statement

as a designer i would like a consistent testimonial/quote component so that i can save time

## Recommendation

Left/right executions needed

## Designs

![screen shot 2018-06-14 at 3 12 01 pm](https://user-images.githubusercontent.com/9420407/41414094-5e01311c-6fe5-11e8-93f1-4f8b81b23a60.png)

SiteBuilder already has this so sketch file should exist with gary chow

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist: No
* Does this pattern exist already but isn’t a community component? (include url) 
https://www.telus.com/en/on/digital

* Which teams/applications do you think would use this improvement?
HS/MOB/B2B
* High impact: No

**Comment by varunj90** [comment] 2020-01-28 16:37
duplicate of https://github.com/telus/tds-community/issues/90

**Closed** 2020-01-28 16:37 UTC
Labels: priority: low, status: design needed 🎨, type: new component :gift:
