### ISSUE TITLE
Dropdown Styling

### ISSUE THREAD

**Issue by telus-kyri** [telus/tds-community#131] opened 2018-10-30 20:16 UTC
At present the look and feel of the TDS Form Select dropdown is inconsistent across browsers. If you compare Chrome, Firefox and Safari you'll notice they all look different from each other. The following ticket contains attachments that illustrate this. Please see https://telusdigital.atlassian.net/browse/DPRBB-234

To reproduce:
Go to any form select dropdown and click in the field. Do this in Chrome, Firefox and Safari.

**Comment by varunj90** [comment] 2018-11-06 14:40
closing this issue as this is a duplicate of https://github.com/telus/tds-core/issues/701

**Closed by varunj90** 2018-11-06 14:40 UTC
