### ISSUE TITLE
new: Carousel / Gallery component

### ISSUE THREAD

**Issue by jackreeves** [telus/tds-community#84] opened 2018-08-13 15:10 UTC
## Problem Statement

As a user i like to see multiple product images easily and visually.
As a designer/dev i dont want to have to reinvent the wheel every time i want to show 3+ images.

## Recommendation

A component that product pages and marketing pages can use to show multiple images. 

additional criteria may include:
- Header, body, cta
- Thumbnails, Chevrons, or dot navigation.
- swipe on touch devices

## Designs

* Screenshots
* Sketch file

## Meta

* Willing to design solution: No
* Willing to develop solution: No
* Has workaround: No
* Do any similar components already exist in TDS (core or community): No
* Does this pattern exist already but isn’t a community component? (include url)

https://www.telus.com/en/bc/internet/fibre/new
https://www.telus.com/en/bc/mobility/accessories/product/jbl-link-10-speaker?linktype=accessorieshomepage
https://www.telus.com/en/bc/mobility/accessories/product/instax-share-sp-3-square-printer
(see instagram looks)

* Which teams/applications do you think would use this improvement?
* High impact: Yes/No

**Comment by jesdavpet** [comment] 2018-08-13 15:17
I'm closing this one as a duplicate of https://github.com/telus/tds-community/issues/50

@jackreeves Please consolidate any further information regarding the request for a Carousel Component there.

**Closed by jesdavpet** 2018-08-13 15:17 UTC
Labels: status: wontfix :no_good_man:, type: duplicate :dancing_men:

**Comment by jesdavpet** [comment] 2018-09-04 18:27
I've added an image of the "gallery" candidate component, removed a confusing link, and updated the title of this issue.

@DougL and @jackreeves are you able to clarify further what the ask is for this issue?

**Comment by theetrain** [comment] 2018-12-03 20:41
Phil is researching viability and accessibility considerations for this.

**Comment by philroberto** [comment] 2018-12-18 14:23
This is ready to be worked on, accessibility has been made aware and provided the opportunity to contribute. Any accessibility requirements may trickle in prior to being picked up for design.
