### ISSUE TITLE
SideNavigation: SideNav can overlap bottom of the page

### ISSUE THREAD

**Issue by Andrew-K-Lam** [telus/tds-community#297] opened 2019-10-09 14:51 UTC
## Description
When the SideNav is near the bottom of the page, opening a submenu will overlap the footer (sticks outside its container).

## Reproduction Steps

1. Go to https://www.telus.com/en/brand-resources/design/motion-principles
2. Close any Submenu's that are open.
3. Scroll to the bottom of the page
4. Open "Motion Principles submenu
5. See the SideNav overlap the footer

## Workaround details
User must scroll so the SideNav updates position

## Meta

- TDS version (npm or DSM): ^2.0.2 --> Will fix for v3.0.1
- Willing to develop solution: Yes
- Has workaround: No
- High impact: No

## Screenshots
![image](https://user-images.githubusercontent.com/931411/66492039-be8b6d00-ea81-11e9-9632-ac144d102d6d.png)

**Comment by varunj90** [comment] 2019-11-12 18:49
Waiting on QA from @fzero :)

**Comment by fzero** [comment] 2019-11-18 15:32
I got some pointers from @theetrain about this - setting aside a few hours to get it done ASAP.

**Comment by varunj90** [comment] 2019-12-02 20:05
reached out to @fzero for QA updates

**Comment by fzero** [comment] 2019-12-03 21:42
Manual QA went fine and the bug seems fixed. I've confirmed accessibility features still work as intended without regressions. The only thing left for me to consider this 100% QA'd is testing on IE11.

**Comment by fzero** [comment] 2019-12-04 19:18
Fix is confirmed to work on all supported platforms including IE11. Ready to go!

**Comment by theetrain** [comment] 2019-12-06 19:26
Released in [`@tds/community-side-navigation@3.0.4`](https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-side-navigation%403.0.4).

**Closed by theetrain** 2019-12-06 19:26 UTC
Labels: type: defect :beetle:
